# Generated by Django 3.1.7 on 2021-07-23 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('touch', '0002_auto_20210722_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Touch',
            new_name='Post',
        ),
    ]
